CREATE TABLE CLIENT.SERVERS(
    ID      BIGINT,
    NAME    VARCHAR(50) NOT NULL,
    IP      VARCHAR(20) NOT NULL,
    PORT    INTEGER NOT NULL,
    STATUS  INTEGER NULL DEFAULT 0,
    PRIMARY KEY(ID)
);

CREATE TABLE CLIENT.SERVER_SERVICE_REF(
    NODE_ID     BIGINT,
    SERVICE_ID  BIGINT,
    PRIMARY KEY(NODE_ID,SERVICE_ID)
);

CREATE TABLE CLIENT.SERVICES(
    ID      BIGINT,
    NAME    VARCHAR(50) NOT NULL,
    LOCAL_IP    VARCHAR(20) NOT NULL,
    LOCAL_PORT  SMALLINT NOT NULL,
    PROXY_PORT  SMALLINT NOT NULL,
    SSL     SMALLINT,
    STATUS  SMALLINT,
    HEALTH_CHECK_URL    VARCHAR(100),
    PRIMARY KEY(ID)
);

CREATE UNIQUE INDEX CLIENT.SERVER_NAME_INDEX ON CLIENT.SERVERS (NAME);

INSERT INTO CLIENT.SERVERS(ID, NAME, IP, PORT) VALUES(1395001077,'PrimaryServer','127.0.0.1',18080);

-- ALTER TABLE CLIENT.SERVERS ADD COLUMN STATUS  INTEGER NULL DEFAULT 0;