CREATE TABLE SERVER.NODES(
    ID      BIGINT,
    NAME    VARCHAR(50) NOT NULL,
    IP      VARCHAR(20) NOT NULL,
    PORT    INTEGER NOT NULL,
    TYPE    SMALLINT DEFAULT 0,
    PRIMARY KEY(ID)
);

CREATE TABLE SERVER.NODE_SERVICE_REF(
    NODE_ID     BIGINT,
    SERVICE_ID  BIGINT,
    PRIMARY KEY(NODE_ID,SERVICE_ID)
);

CREATE TABLE SERVER.SERVICES(
    ID      BIGINT,
    NAME    VARCHAR(50) NOT NULL,
    PROXY_PORT  SMALLINT NOT NULL,
    SSL     SMALLINT,
    STATUS  SMALLINT,
    PRIMARY KEY(ID)
);